#' @include components-parameter.R
#' @include components-reference.R
NULL

#' A collection of parameters and references to parameters
#'
#' The object provides a list of [class_parameter()] (or [class_reference()]
#' pointing to [class_parameter()]).
#'
#' @param ... One or more [abstract_security_scheme()] objects or a list of such
#'   objects. These objects must be generated by
#'   [class_api_key_security_scheme()] or [class_oauth2_security_scheme()]
#'   (`http_security_scheme()` and `open_id_connect_security_scheme()` coming
#'   soon).
#'
#' @return A `security_scheme_details` object, which is a validated list of
#'   [abstract_security_scheme()] objects.
#' @export
class_parameters <- S7::new_class(
  "parameters",
  package = "rapid",
  parent = class_list,
  constructor = function(...) {
    if (...length() == 1 && is.list(..1)) {
      return(S7::new_object(..1))
    }
    S7::new_object(list(...))
  },
  validator = function(self) {
    bad_parameters <- !purrr::map_lgl(
      S7::S7_data(self),
      ~ S7_inherits(.x, class_parameter) | S7_inherits(.x, class_reference)
    )
    if (any(bad_parameters)) {
      bad_locations <- which(bad_parameters)
      c(
        cli::format_inline(
          "All values must be {.cls parameter} or {.cls reference} objects."
        ),
        cli::format_inline("Bad values at {bad_locations}.")
      )
    }
  }
)
