#' Details of API security schemes
#'
#' The object provides a list of details of security schemes for the API. Each
#' element within the list is a
#'
#' @param ... One or more [security_scheme()] objects or a list of such objects.
#'   These objects must be generated by [api_key_security_scheme()] or
#'   [oauth2_security_scheme()] (`http_security_scheme()` and
#'   `open_id_connect_security_scheme()` coming soon).
#'
#' @return A [security_scheme_details()] object, which is a validated list of
#'   [security_scheme()] objects.
#' @export
#'
#' @examples
#' security_scheme_details(
#'   oauth2_security_scheme(
#'     password_flow = oauth2_token_flow(
#'       token_url = "/account/authorization",
#'       scopes = scopes(
#'         name = c("Catalog", "Commerce", "Playback", "Settings"),
#'         description = c(
#'           "Access all read-only content",
#'           "Perform account-level transactions",
#'           "Allow playback of restricted content",
#'           "Modify account settings"
#'         )
#'       )
#'     )
#'   ),
#'   oauth2_security_scheme(
#'     password_flow = oauth2_token_flow(
#'       token_url = "/account/profile/authorization",
#'       scopes = scopes(
#'         name = "Catalog",
#'         description = "Modify profile preferences and activity (bookmarks, watch list)"
#'       )
#'     )
#'   ),
#'   api_key_security_scheme(
#'     parameter_name = "authorization",
#'     location = "header"
#'   ),
#'   api_key_security_scheme(
#'     parameter_name = "authorization",
#'     location = "header"
#'   )
#' )
security_scheme_details <- S7::new_class(
  "security_scheme_details",
  package = "rapid",
  parent = class_list,
  constructor = function(...) {
    if (...length() == 1 && is.list(..1)) {
      return(S7::new_object(..1))
    }
    S7::new_object(list(...))
  },
  validator = function(self) {
    bad_security_schemes <- !purrr::map_lgl(
      S7::S7_data(self),
      ~ S7::S7_inherits(.x, security_scheme) || is.null(.x)
    )
    if (any(bad_security_schemes)) {
      bad_locations <- which(bad_security_schemes)
      c(
        cli::format_inline(
          "All values must be {.cls security_scheme} objects."
        ),
        cli::format_inline("Bad values at {bad_locations}.")
      )
    }
  }
)

#' Coerce lists to security_scheme_details objects
#'
#' `as_security_scheme_details()` turns an existing object into a
#' `security_scheme_details` object. This is in contrast with
#' [security_scheme_details()], which builds a `security_scheme_details` from
#' individual properties.
#'
#' @inheritParams rlang::args_dots_empty
#' @param x The object to coerce. Must be empty or be a named list, where each
#'   element describes a security scheme object. This object should describe the
#'   security schemes for a single API.
#'
#' @return A `security_scheme_details` object as returned by
#'   [security_scheme_details()].
#' @export
#'
#' @examples
#' as_security_scheme_details()
#' as_security_scheme_details(
#'   list(
#'     accountAuth = list(
#'       description = "Account JWT token",
#'       flows = list(
#'         password = list(
#'           scopes = list(
#'             Catalog = "Access all read-only content",
#'             Commerce = "Perform account-level transactions",
#'             Playback = "Allow playback of restricted content",
#'             Settings = "Modify account settings"
#'           ),
#'           tokenUrl = "/account/authorization"
#'         )
#'       ),
#'       type = "oauth2"
#'     ),
#'     profileAuth = list(
#'       description = "Profile JWT token",
#'       flows = list(
#'         password = list(
#'           scopes = list(
#'             Catalog = "Modify profile preferences and activity (bookmarks, watch list)"
#'           ),
#'           tokenUrl = "/account/profile/authorization"
#'         )
#'       ),
#'       type = "oauth2"
#'     ),
#'     resetPasswordAuth = list(
#'       `in` = "header",
#'       name = "authorization",
#'       type = "apiKey"
#'     ),
#'     verifyEmailAuth = list(
#'       `in` = "header",
#'       name = "authorization",
#'       type = "apiKey"
#'     )
#'   )
#' )
as_security_scheme_details <- S7::new_generic(
  "as_security_scheme_details",
  dispatch_args = "x"
)

S7::method(as_security_scheme_details, security_scheme_details) <- function(x) {
  x
}

S7::method(as_security_scheme_details, class_list) <- function(x) {
  if (!length(x) || !any(lengths(x))) {
    return(security_scheme_details())
  }
  security_scheme_details(
    purrr::map(unname(x), as_security_scheme)
  )
}

S7::method(as_security_scheme_details, class_missing | NULL | S7::new_S3_class("S7_missing")) <- function(x) {
  security_scheme_details()
}

S7::method(as_security_scheme_details, class_any) <- function(x, ..., arg = rlang::caller_arg(x)) {
  cli::cli_abort(
    "Can't coerce {.arg {arg}} {.cls {class(x)}} to {.cls security_scheme_details}."
  )
}
