## usethis namespace: start
#' @importFrom cli format_inline
#' @importFrom glue glue
#' @importFrom rlang %||%
#' @importFrom rlang check_dots_empty
#' @importFrom S7 class_any
#' @importFrom S7 class_character
#' @importFrom S7 class_factor
#' @importFrom S7 class_list
#' @importFrom S7 class_logical
#' @importFrom S7 prop
#' @importFrom S7 prop<-
#' @importFrom S7 S7_inherits
#' @importFrom S7 validate
#' @importFrom stbl stabilize_chr
#' @importFrom stbl stabilize_chr_scalar
#' @importFrom stbl stabilize_fct
#' @importFrom stbl stabilize_lgl_scalar
#' @importFrom xml2 url_absolute
#' @importFrom yaml read_yaml
## usethis namespace: end
NULL
